"""
This module defines the Hydrogen Electrolyzer input power and auxillery systems code.
"""
import numpy as np
from attrs import define

from .type_dec import FromDictMixin


@define
class Operator(FromDictMixin):
    # Power/Turbine Parameters

    def convert_ac_to_dc(power_ac_in):
        """
        # Reference: https://magna-power.com/products/magnadc/mt

        Inputs:
            power_ac_in: power (W~AC) generated by turbine (or farm)
        Returns:
            power_dc_out: power (W-DC) provided to the electrolyzer
        """

        # Generic parameters
        a = 0.000055
        b = 1.046825
        c = 18.856015

        Pac_kw = power_ac_in / 1000.0

        Pdc_kw_plus = (-b + np.sqrt(b**2 - 4 * a * (c - Pac_kw))) / (2 * a)
        Pdc_kw_minus = (-b - np.sqrt(b**2 - 4 * a * (c - Pac_kw))) / (2 * a)

        power_dc_out_plus = Pdc_kw_plus * 1000.0
        power_dc_out_minus = Pdc_kw_minus * 1000.0

        return power_dc_out_plus, power_dc_out_minus
